---
title: "Supplementary Figure S2"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F, fig.width = 5.5)

options(knitr.table.format = "latex")

windowsFonts(Times=windowsFont("TT Times New Roman"))
```


```{r load packages}
suppressPackageStartupMessages({
  library(ggridges)
  library(here)
  library(tidyverse)
})
```

```{r}
fish <- read_csv(here("data","lionfish_data.csv"), col_types = cols()) %>% 
  group_by(Id, Site, Location, Latitude, Longitude, Depth_m) %>% 
  summarize(Length = 10*mean(TotalLength_cm),
            Weight = mean(TotalWeigth_gr),
            Stomach = mean(StomachLength_cm)) %>% 
  ungroup()

review <- read.csv(here::here("data", "biometric_review.csv"),
                   stringsAsFactors = F,
                   strip.white = T,
                   blank.lines.skip = T) %>% 
  mutate(c = log10(a),
         Gender2 = case_when(Gender == "Male" ~ "M",
                             Gender == "Female" ~ "F",
                             TRUE ~ "B"))
```

```{r}
review %>% 
  mutate(Length = list(fish$Length),
         Weight = list(fish$Weight)) %>% 
  unnest() %>% 
  mutate(pWeight = a*(Length^b),
    Biomass_ratio = pWeight / Weight) %>% 
  mutate(Study = paste0(Study, " (", Gender_site, ")")) %>%
  transform(Study = reorder(Study, -Biomass_ratio),
            Study_id = reorder(Study_id, -Biomass_ratio)) %>%
  ggplot(aes(x = Biomass_ratio, y = Study, fill = Study)) +
  geom_density_ridges(alpha = 0.5, size = 1) +
  geom_vline(xintercept = 1, linetype = "dashed", size = 1, color = "red") +
  theme_bw() +
  theme(text = element_text(family = "Times"),
        legend.position = "none",
        legend.text = element_text(size = 10),
        legend.background = element_rect(fill = "transparent"),
        axis.text = element_text(size = 10)) +
    labs(x = "Weight ratio (Predicted/Observed)", y = "") +
  scale_fill_viridis_d()
```


